apiVersion: v1
kind: Service
metadata:
  name: low-code workflow automation platform
spec:
  selector:
    app: low-code workflow automation platform
  ports:
  - port: 
        8000
        targetPort: 8000
  type: ClusterIP
